### ISSUE TITLE
Storybook Component Documentation Update - Refactor the RadioInput component story

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#1000]
## Description
The RadioInput component's story is configured so that it is wrapped in the `<RadioInputStoryHelper />`. The StoryHelper is used to manage the state and functionality of the component. 
The Code option in the component Docs page serves as a reference for how to use the component. With this HOC component wrapping it we cannot see the example of how to use this component. 
To fix this, we can move the helper and move that logic into the component story, so that it allows for the `RadioInput` component code to fully display. 

The current configuration of the RadioInput component's story involves a <RadioInputStoryHelper /> wrapper. This wrapper plays a crucial role in overseeing the component's state and functionality.

There are some issues with how it displays the component's code in the Code tab in Storybook. This option essentially provides a guide on how to use the component. Unfortunately, the usage example of this component is obscured by the higher-order component (HOC) that is encompassing it - RadioInputStoryHelper.

<img width="1136" alt="Screenshot 2023-09-19 at 1 52 30 PM" src="https://github.com/d2iq/ui-kit/assets/34781875/57022e10-c58e-4b88-9f45-df1484bad386">

To address this issue, a suggested solution entails repositioning this operational logic within the story designed for the RadioInput. By taking this step, the RadioInput component's code will become visible and accessible.

For an example of how a component was refactored in a similar way you can reference this work: https://github.com/d2iq/ui-kit/pull/989 

If this is your first experience working with Storybook stories, they have [great documentation to reference](https://storybook.js.org/docs/react/writing-stories/introduction), along with the other story files we have throughout the project. 

**Acceptance Criteria** 
Update the `RadioInput.stories.tsx` file so that the code example will display how to use the component. 

<hr> 

### Contribution Guide
If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by kavandalal** [comment]
Hi @nataliepina , I tried refactoring the code. I was successfully able to get the RadioInput component's code visible.

This should be the ideal output right ?
![image](https://github.com/d2iq/ui-kit/assets/67893720/9a8bdbca-974a-4294-b050-e14106364292)

**Comment by nataliepina** [comment]
@kavandalal yes, that's exactly what we're looking for thank you! I can assign this to you and feel free to create a PR when you're ready.

**Comment by kavandalal** [comment]
@nataliepina  I should follow [this](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) approach. right ?

**Comment by nataliepina** [comment]
> @nataliepina I should follow [this](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) approach. right ?

Yes that's correct. Please let us know if you have any questions. Thank you for contributing to UI Kit ⭐

**Comment by kavandalal** [comment]
I will create PR shortly, but just to remove error from the description, under "Acceptance Criteria" you have written to update `CheckboxInput.stories.tsx` .

**Comment by nataliepina** [comment]
> I will create PR shortly, but just to remove error from the description, under "Acceptance Criteria" you have written to update `CheckboxInput.stories.tsx` .

Thank you, i've corrected that now. We have another issue to correct the CheckboxInput in a similar way.

**Comment by kavandalal** [comment]
@nataliepina PR created, Thanks for giving the link to other (refactor)[https://github.com/d2iq/ui-kit/pull/989] commit 👍
