### ISSUE TITLE
Storybook Component Documentation Update - Refactor the SegmentedControl component story

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#1002]
## Description
The SegmentedControl component's story is configured so that it is wrapped in the `<SegmentedControlStoryHelper />`. The StoryHelper is used to manage the state and functionality of the component. 
The Code option in the component Docs page serves as a reference for how to use the component. With this HOC component wrapping it we cannot see the example of how to use this component. 
To fix this, we can move the helper and move that logic into the component story, so that it allows for the `SegmentedControl` component code to fully display. 

The current configuration of the SegmentedControl component's story involves a <SegmentedControlStoryHelper /> wrapper. This wrapper plays a crucial role in overseeing the component's state and functionality.

There are some issues with how it displays the component's code in the Code tab in Storybook. This option essentially provides a guide on how to use the component. Unfortunately, the usage example of this component is obscured by the higher-order component (HOC) that is encompassing it - SegmentedControlStoryHelper.

<img width="1290" alt="Screenshot 2023-09-20 at 10 43 19 AM" src="https://github.com/d2iq/ui-kit/assets/34781875/ef687f61-50ea-4efd-a07f-d70898f40d2d">
See the screenshot above and how the helper is displaying but not showing how to use the actual component. 

To address this issue, a suggested solution entails repositioning this operational logic within the story designed for the SegmentedControl. By taking this step, the SegmentedControl component's code will become visible and accessible.

For an example of how a component was refactored in a similar way you can reference this work: https://github.com/d2iq/ui-kit/pull/989 

If this is your first experience working with Storybook stories, they have [great documentation to reference](https://storybook.js.org/docs/react/writing-stories/introduction), along with the other story files we have throughout the project. 

**Acceptance Criteria** 
Update the `SegmentedControl.stories.tsx` file so that the code example will display how to use the component. 

<hr> 

### Contribution Guide
If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by nataliepina** [comment]
Hi @electron97 I see you've created a pull request for this so I will assign it to you.

**Comment by nataliepina** [comment]
@electron97 I cannot assign issues to you unless you comment on the issue first. We ask that you ask to have issues assigned for this reason, also so we don't duplicate work. Comment back if you'd like me to assign so you can get your Hacktoberfest credit if you are participating. Cheers!

**Comment by electron97** [comment]
Hey @nataliepina ,
Thanks for clarifying. Could you please assign this issue to me?

Thanks!
