### ISSUE TITLE
Storybook Component Documentation Update - Refactor the ToggleBoxInputList component story

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#1003]
## Description
The ToggleBoxInputList component's story is configured so that it is wrapped in the `<ToggleBoxInputListStoryHelper />`. The StoryHelper is used to manage the state and functionality of the component.
The Code option in the component Docs page serves as a reference for how to use the component. With this HOC component wrapping it we cannot see the example of how to use this component.
To fix this, we can move the helper and move that logic into the component story, so that it allows for the `ToggleBoxInputList` component code to fully display.

The current configuration of the ToggleBoxInputList component's story involves a <ToggleBoxInputListStoryHelper /> wrapper. This wrapper plays a crucial role in overseeing the component's state and functionality.

There are some issues with how it displays the component's code in the Code tab in Storybook. This option essentially provides a guide on how to use the component. Unfortunately, the usage example of this component is obscured by the higher-order component (HOC) that is encompassing it - ToggleBoxInputListStoryHelper.

<img width="1280" alt="Screenshot 2023-09-20 at 10 58 07 AM" src="https://github.com/d2iq/ui-kit/assets/34781875/d102d23b-0a03-403e-9fd7-af6446de0877">

To address this issue, a suggested solution entails repositioning this operational logic within the story designed for the ToggleBoxInputList. By taking this step, the ToggleBoxInputList component's code will become visible and accessible.

For an example of how a component was refactored in a similar way you can reference this work: https://github.com/d2iq/ui-kit/pull/989

If this is your first experience working with Storybook stories, they have [great documentation to reference](https://storybook.js.org/docs/react/writing-stories/introduction), along with the other story files we have throughout the project.

**Acceptance Criteria**
Update the `ToggleBoxInputList.stories.tsx` file so that the code example will display how to use the component.

<hr>

### Contribution Guide
If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by Chirag-Nanda** [comment]
Can this issue be assigned to me

**Comment by Chirag-Nanda** [comment]
I have made a pull request, please check and review it.
