### ISSUE TITLE
Refactor FormFieldWrapper components

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#1012]
## Description
We have a shared component called _FormFieldWrapper_. There are some parts of it that use old patterns that we'd like to update. 
There are these `get` getter type functions that return JSX. Really these should be components that return JSX in accordance with modern patters. 

This would would be to assess those parts of FormFieldWrapper and refactor and improve them. 

For example, this getHintContent, should be a component called HintContent:

```
  const getHintContent = hintContent => {
    return hintContent ? (
      <span
        id={getHintContentId()}
        className={cx(
          tintContentSecondary,
          display("block"),
          padding("top", "xxs"),
          textSize("s")
        )}
      >
        {hintContent}
      </span>
    ) : null;
  };
```

The same thing for getValidationErrors.

With these updates make sure to do regression tests and everything should work in the exact same way. 

<hr> 

### Contribution Guide
If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by Chirag-Nanda** [comment]
Can I be assigned this issue?

**Comment by mstruebing** [comment]
@Chirag-Nanda sure - I've assigned you to that issue.

**Comment by Chirag-Nanda** [comment]
can you explain a bit more on what exactly is the job needed to be done? Should I replace the entire getHintContent by HintContent?

**Comment by nataliepina** [comment]
> can you explain a bit more on what exactly is the job needed to be done? Should I replace the entire getHintContent by HintContent?

That's correct. `getHintContent` should become a functional component and you can replace it's usage everywhere possible and then remove the getHintContent function once that is completed.  You can isolate the work for getHintContent into one pull request and you can do the validation errors in a separate pull request if you have interest in refactoring that one as well. Let me know if you have any other questions around that all.

**Comment by Chirag-Nanda** [comment]
@nataliepina I have made the changes can you please verify them?
