### ISSUE TITLE
Dependency Update - fork-ts-checker-webpack-plugin version 9

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#1057]
## Description
We are a major version behind on `fork-ts-checker-webpack-plugin`.
Since it is a major version upgrade, there may be some breaking changes. Read over the release notes and be sure to test everything out to make sure there haven't been any regressions . 

`fork-ts-checker-webpack-plugin      ^8.0.0  →    ^9.0.0`

<hr> 

### Contribution Guide
*Please first request that this issue will be assigned to you and begin work once the issue has been assigned to you.*
🎃 Happy Hacktoberfest!

If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by IamSudhir-Kumar** [comment]
Hi, @nataliepina can you assign this issue to me please !!!

**Comment by nataliepina** [comment]
I've assigned it over to you, thanks!
