### ISSUE TITLE
Add className properties to components

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#893]
# Description
We'd like to have access to `className` as a property on our components to pass in custom style overrides.
You'll need to add it to the component in a sensible location and include a type definition for it. 

Refer to the use of `className` in the `Box` component as an example. 

## Acceptance Criteria

Go through the components and add an optional `className` property if it doesn't already exist. 

## How to Contribute 
Please review the [contributing documentation](https://github.com/dcos-labs/ui-kit/blob/main/CONTRIBUTING.md) beforehand. 

Steps to Contribute:
1. [Fork the repository](https://github.com/dcos-labs/ui-kit/fork).
2. Clone it to your local system.
3. Create a new branch.
4. Make your changes. Make sure that tests are still passing. To update snapshot tests, run `npm run test -- -u` and include the updated tests in your commit.
5. Commit your changes.  When committing prefix your commit message with the appropriate conventional commit type. For example, `feat: brief explanation of changes made`. 
6. Push up your changes. In GitHub, click the compare & pull request button to begin drafting your pull request.
7. Fill out the pull request form and attach the "ready for review" label when complete.

**Comment by davidtaing** [comment]
Hey @nataliepina, it's been a while!

I'd like to work on this one. But first, I want to confirm what the expectations are (in terms of timeframes)?

I have a feeling that I will be busy with other programming related commitments, so this may take a few weeks from my side.

As clarification, I'm assuming that we'll need to add classNames for all components.

**Comment by nataliepina** [comment]
Hey @davidtaing thanks for checking back in on our open issues! 

There isn't any expected timeframe on this one. This has been in our backlog of to-dos for a while. Some components have a `className` prop already but there are many that don't. If you'd like, you could dedicate each PR to a specific component so you could do them when you have some free time and if you get busy no worries you can come back and do some more later on. Or if you'd like to group some together you could do that as well. Whatever works best for you there. Any contributions would be helpful on this. I'll probably be jumping in and updating some of these myself if I can find some extra time to dedicate to it.

Thank you for your interest! I'll likely be creating even more open issues in January 🎉

**Comment by davidtaing** [comment]
Cool, cool @nataliepina.

I'll try to chip away at this. I'll lean towards small groupings of components.

We'll be in touch and hope you have a lovely holiday season!

**Comment by nataliepina** [comment]
Thanks @davidtaing I'll assign it to you. Happy holidays!

**Comment by davidtaing** [comment]
Hi @nataliepina,
Hope you had a lovely holiday season!

I've started working on this issue again and I wanted to give you a quick status update. 

My plan is to do a majority of the work (80% - 90%) but leave some components outstanding so that we can provide more opportunities for people to get involved.

Of course, if no one comes onboard, I'll be happy to finish the remainder for you.

What are you thoughts on this approach?

**Comment by nataliepina** [comment]
@davidtaing That sounds like a good plan. Feel free to do as many components as you'd like and we'll take the rest from there. 

Hope you had a great holiday as well!

**Comment by davidtaing** [comment]
Thanks guys. Always a pleasure to help!
