### ISSUE TITLE
Refactor the use of deprecated `onKeyPress`

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#915]
# Description

We have uses of `onKeyPress` in the application that need to be updated. It is used in the `Clickable`, `ButtonCard`, and `TextInputWithBadges` components. Keydown is an alternative to keypress. 

Resource for Keyboard Events: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
Resource for Keyboard Events in React: https://reactjs.org/docs/events.html#keyboard-events

<img width="590" alt="Screenshot 2023-01-11 at 12 50 25 PM" src="https://user-images.githubusercontent.com/34781875/211893719-172686d9-5277-4f0b-bb3d-43827fda5ad9.png">

## Acceptance Criteria

Update anywhere that onKeyPress is used. 

## How to Contribute 
Please review the [contributing documentation](https://github.com/dcos-labs/ui-kit/blob/main/CONTRIBUTING.md) beforehand. 

Steps to Contribute:
1. [Fork the repository](https://github.com/dcos-labs/ui-kit/fork).
2. Clone it to your local system.
3. Create a new branch.
4. Make your changes. Make sure that tests are still passing. To update snapshot tests, run `npm run test -- -u` and include the updated tests in your commit.
5. Commit your changes.  When committing prefix your commit message with the appropriate conventional commit type. For example, `refactor: <component_name> tests`. 
6. Push up your changes. In GitHub, click the compare & pull request button to begin drafting your pull request.
7. Fill out the pull request form and attach the "ready for review" label when complete.

**Comment by derekhassan** [comment]
Hi @nataliepina, I'd love to grab this issue!
