### ISSUE TITLE
Refactor the use of `defaultProps` to instead use fallback default values

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#926]
# Description

In older versions of React, we had an explicit defaultProps property we could apply to components. 

We still have some references to defaultProps throughout UI Kit that should be updated to use fallbacks like the other components. This may require some component refactoring. 

For example:
```
const HeadingText1 = (props: HeadingTextProps) => (
  <Text weight="medium" size="xl" data-cy="headingText1" {...props} />
);

HeadingText1.defaultProps = {
  align: "inherit",
  color: themeTextColorPrimary,
  wrap: "wrap",
  tag: "h3"
};
```

can be refactored to:
```
const HeadingText1 = ({
  align = "inherit",
  color = themeTextColorPrimary,
  wrap = "wrap",
  tag = "h3",
  ...props
}: HeadingTextProps) => (
  <Text weight="medium" size="xl" data-cy="headingText1" {...props} />
);
```

## Acceptance Criteria

Update anywhere that `defaultProps` is used and opt for fallback defaults set where props are destructured. 

<hr> 

## How to Contribute 
Please review the [contributing documentation](https://github.com/dcos-labs/ui-kit/blob/main/CONTRIBUTING.md) beforehand. 

Steps to Contribute:
1. [Fork the repository](https://github.com/dcos-labs/ui-kit/fork).
2. Clone it to your local system.
3. Create a new branch.
4. Make your changes. Make sure that tests are still passing. To update snapshot tests, run `npm run test -- -u` and include the updated tests in your commit.
5. Commit your changes.  When committing prefix your commit message with the appropriate conventional commit type. For example, `refactor: <component_name> tests`. 
6. Push up your changes. In GitHub, click the compare & pull request button to begin drafting your pull request.
7. Fill out the pull request form, and it will be reviewed by the UI Team.

**Comment by derekhassan** [comment]
Hi @nataliepina, I'd love to take this issue!

**Comment by nataliepina** [comment]
Assigning it over to you, thanks for your interest in contributing again Derek! 🎉

**Comment by nataliepina** [comment]
Hi @derekhassan how is this task going? Please let us know if you need any help with it!

**Comment by derekhassan** [comment]
Hi @nataliepina, thanks for reaching out! Apologies for the delay, I haven't had much time to work on this issue. Things are going good so far and I expect to have a PR up by Saturday 👍
