### ISSUE TITLE
CSS fix for table column re-sizer

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#933]
# Description
When a user clicks on the column re-sizer, a vertical gray line (center aligned to the re-sizer) should appear to indicate the boundary of the column being resized.
The gray line is the same gray as what we use on the table row border.

Here is a design example:

![table-resizer](https://user-images.githubusercontent.com/34781875/224999871-6803cf9e-fb81-4a1f-8d75-085b82a4ab81.png)

### Contribution Guide
Please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) Guide beforehand.

**Comment by piyushac123** [comment]
@nataliepina may I take this up?

**Comment by piyushac123** [comment]
I was not able to find sections mentioned in video (after executing code locally), can u guide me?

**Comment by nataliepina** [comment]
@piyushac123 The video is the component being used in an application and helps to describe the expected behavior. You will be able to see the table component in a similar way through the [Table component stories](https://d2iq.github.io/ui-kit/?path=/story/data-listing-table--default). I will add some clarity to the description on this issue.
What we'd like to have implemented here is a vertical line that will better indicate how the columns are shifting. 
Just as a heads up this will be a pretty challenging CSS-related task. Please let me know if you still feel you'd like to try it out. Thanks!

**Comment by piyushac123** [comment]
Got it, I will try this, if comfortable will let u know

**Comment by nataliepina** [comment]
Awesome. Thanks @piyushac123, please let me know if you have any questions.

**Comment by nataliepina** [comment]
Any progress on this @piyushac123? We are tracking the progress of some of these tasks to ensure they are completed. Would you be able to complete this within the next 2 weeks?

**Comment by piyushac123** [comment]
Hey @nataliepina sorry for late reply, currently I am going some what busy, so, will not be able to complete this issue. I will try to complete other assigned issue as soon as possible.
