### ISSUE TITLE
Update the `@testing-library/react` dependency

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#940]
# Description
We are a major version behind on React Testing Library. Update the dependency to the latest version -> 14.0.0. If there are any issue with our unit tests, please fix them. 

`@testing-library/react            13.4.0  →  14.0.0
`
<hr> 

### Contribution Guide
Please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by Yasir761** [comment]
I've updated the version but it showing some errors while I'm doing the commit.

**Comment by mstruebing** [comment]
Hey @Yasir761 what kind of errors do you see?
Can you paste the CLI output?

**Comment by Yasir761** [comment]
> @d2iq/ui-kit@0.0.0-dev+semantically-released test:types
> tsc -p tsconfig.types.json

.storybook/docs/components/WelcomeBanner.tsx(3,32): error TS2307: Cannot find module '../../../packages/design-tokens/build/js/designTokens' or its corresponding type declarations.
and many more like this error.

**Comment by nataliepina** [comment]
@Yasir761 Could you double-check that you've run `npm i` and try out running `npm run dist`?

You can run `npm run test:types` in the CLI to do some debugging. 
I've tested out the change on my end and I was able to create a commit without any errors, so it seems that you may be missing something in getting started with the project. Are you able to start storybook?

**Comment by Yasir761** [comment]
@nataliepina Yes, I was able to start the storybook and also did some debugging but, it still the giving same output.
![Screenshot 2023-03-12 220256](https://user-images.githubusercontent.com/74600745/224558701-7d7473eb-c11b-492c-8774-4e87156f47e3.png)

**Comment by nataliepina** [comment]
I see the issue here @Yasir761. We have commit message linting. You will need to prefix your commit message with a [commit type](https://github.com/d2iq/ui-kit/blob/main/CONTRIBUTING.md#commit-types). For example `git commit -m "chore: update the version of react testing library`. There is also a character limit for that commit message so you may need to adjust as needed. This is all outlined in more detail in the [How to Contribute Guide](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute). 

Let me know if you're still having issues with committing after that!

**Comment by Yasir761** [comment]
@nataliepina , It still shows the same message.

**Comment by nataliepina** [comment]
Could you review the [steps to contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute#steps-to-contribute) one last time and make sure you've completed each step?
Then if you encounter an error, could you outline what you've entered in the CLI and send a screenshot here with everything in view? 

You should be able to commit this after a `git add .` and then `git commit -m "chore: update the version of react testing library"`. You will need to wait a minute or two and then it will finish committing. Then you can `git push`. 

I have tested it out with those commands and here is a successful flow:
<img width="905" alt="Screenshot 2023-03-13 at 7 11 45 AM" src="https://user-images.githubusercontent.com/34781875/224698170-83e10679-1ae4-4c1d-a7a4-e000c3537969.png">

**Comment by Yasir761** [comment]
I tried all but now it showing this 
![Screenshot 2023-03-13 223723](https://user-images.githubusercontent.com/74600745/224774619-c0943cd4-36f7-43a6-ace1-9ab57c54e332.png)

**Comment by nataliepina** [comment]
Judging by the errors it looks like you have something extra that needs to be deleted that is throwing off the formatting. These errors are triggered by [Prettier](https://prettier.io/) which we use to format the code. Try to run `npm run setup:git-hooks` first. Our pre-commit hook runs `npm run test:types && npm run lint` so you can try to run those locally as well to check if you have everything set up correctly. You can run `npm run format` to format the code which may fix the issue. I also might suggest adding the [Prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) if you're using VSCode and set up Format on Save, so it will correct any formatting issues for you. Make sure that the only 2 files that are changed are package.json and package-lock.json and that both of them are committed.

If all of that fails, you may want to remove your changes altogether and try again. Or look over the changes and compare the differences to see if there is an extra character or something formatted incorrectly.

An overview of the changes to implement the new version: 
1. Set up the working local development environment, which you probably have already.
2. In the CLI, at the root run `npm i @testing-library/react --save-exact`
3. Look over the changes and if everything is working you can now commit the changes.

**Comment by nataliepina** [comment]
Hi @Yasir761 were you able to resolve the issues and able to commit? Please let us know if you're still encountering anything else with that.

**Comment by Yasir761** [comment]
I try everything but don't know why it is showing same error to me

**Comment by nataliepina** [comment]
I'm sorry you're encountering problems with this! I'm going to attempt this update again to make sure there aren't any problems on our end, and I will update it if all goes well. For that reason, I will close this issue out. We should be adding more issues here soon if you'd like another opportunity to contribute. Thanks for your interest!
