### ISSUE TITLE
Update `downshift` to the latest version

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#942]
# Description
We are a major version behind on `downshift`. Update the [downshift](https://www.npmjs.com/package/downshift) dependency to the latest version. 
Since it is a major version upgrade, there may be some things to fix. I suggest reading over the release notes to see what has changed to ensure there is not a breaking change. Run regression tests on the components. 

Please use the exact version. For example, `^7.3.2` 🚫  |  `7.3.2` ✅ 

`downshift   6.1.12  →   7.3.2`

<hr> 

### Contribution Guide
If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by piyushac123** [comment]
@nataliepina may I take this?

**Comment by nataliepina** [comment]
Yes, thank you 👍🏻
