### ISSUE TITLE
Update `wait-on` dependency to the latest version

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#943]
# Description
We are a major version behind on `wait-on`. Update the [wait-on](https://www.npmjs.com/package/wait-on) dependency to the latest version. 
Since it is a major version upgrade, there may be some things to fix. I suggest reading over the release notes to see what has changed to ensure there is not a breaking change. Run regression tests on the components and run the tests.  

Please use the exact version. For example, `^ 7.0.1` 🚫  |  ` 7.0.1` ✅ 

`wait-on    6.0.1  →   7.0.1`

<hr> 

### Contribution Guide
If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by piyushac123** [comment]
@nataliepina may I take this?
