### ISSUE TITLE
Update `fork-ts-checker-webpack-plugin` to the latest version

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#944]
# Description
We are a major version behind on `fork-ts-checker-webpack-plugin`. Update the [fork-ts-checker-webpack-plugin](https://www.npmjs.com/package/fork-ts-checker-webpack-plugin) dependency to the latest version. 
Since it is a major version upgrade, there may be some things to fix. I suggest reading over the release notes to see what has changed to ensure there is not a breaking change. Make sure that our Webpack build is working as expected with this update. 

Please use the exact version. For example, `^8.0.0` 🚫  |  `8.0.0` ✅ 

`fork-ts-checker-webpack-plugin   6.4.0  →   8.0.0`

<hr> 

### Contribution Guide
If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by piyushac123** [comment]
@nataliepina may I take this?

**Comment by nataliepina** [comment]
Sure, thanks @piyushac123.
