### ISSUE TITLE
Update the `svgo` dependency

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#945]
# Description
We are a major version behind on `svgo`. Update the [svgo](https://www.npmjs.com/package/svgo) dependency to the latest version. 
Since it is a major version upgrade, there may be some things to fix. I suggest reading over the release notes to see what has changed to ensure there is not a breaking change. This dependency is used for our component library icons, be sure that they are working as expected. 

Please use the exact version. For example, `^3.0.2` 🚫  |  `3.0.2` ✅ 

`svgo 2.8.0  →   3.0.2`

<hr> 

### Contribution Guide
If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by piyushac123** [comment]
@nataliepina may I take this?

**Comment by piyushac123** [comment]
After upgrading to version - 3.0.2 - I am facing following error. Can u help?
```
/Users/piyush/Documents/contribution/ui-kit/node_modules/svgo/lib/svgo.js:37
        throw Error(`Unknown builtin plugin "${plugin.name}" specified.`);
        ^

Error: Unknown builtin plugin "cleanupIDs" specified.
    at resolvePluginConfig (/Users/piyush/Documents/contribution/ui-kit/node_modules/svgo/lib/svgo.js:37:15)
    at Array.map (<anonymous>)
    at optimize (/Users/piyush/Documents/contribution/ui-kit/node_modules/svgo/lib/svgo.js:73:37)
    at optimize (/Users/piyush/Documents/contribution/ui-kit/node_modules/svgo/lib/svgo-node.js:76:10)
    at /Users/piyush/Documents/contribution/ui-kit/packages/icons/scripts/build.js:50:20
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

**Comment by nataliepina** [comment]
This update is going to be a bit more challenging compared to the rest. You'll have to do some troubleshooting and research the errors you're encountering. 
I'd suggest looking at where `cleanupIDs` is used in build.js and you may need to make an update there. 
Here is more information on [troubleshooting ](https://github.com/svg/svgo#troubleshooting) with svgo.

**Comment by piyushac123** [comment]
Sure, thanks, will check out

**Comment by nataliepina** [comment]
Hi @piyushac123 how is this one going? I'm sure it's challenging. Are you encountering any notable issues?

**Comment by nataliepina** [comment]
No problem! Feel free to keep working on this. Just wanted to make sure to offer support, or note if any issues are encountered. Let us know if so, thanks!

**Comment by piyushac123** [comment]
Sure, thanks @nataliepina :)

**Comment by nataliepina** [comment]
> Sure, thanks @nataliepina :)

Hi, @piyushac123 it's been about a month now since your last update. Were you able to create these changes?
If there isn't a pull request by the end of the week, I'll be closing out this issue so that another person is able to contribute.
