### ISSUE TITLE
Update the `downshift` library to the latest version

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#985]
## Description
We are a major version behind on `downshift`. Update the [downshift](https://www.npmjs.com/package/downshift) dependency to the latest version. 
Since it is a major version upgrade, there may be some things to fix. I suggest reading over the release notes to see what has changed to ensure there is not a breaking change. Run regression tests on the components. 

Update downshift to the latest version: ` 7.6.0  →  ^8.1.0`

<hr> 

### Contribution Guide
If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by Utkarsh212** [comment]
Please assign this to me.
