### ISSUE TITLE
Update @testing-library/jest-dom to version 6

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#987]
## Description
We are a major version behind on `@testing-library/jest-dom`. Update the [@testing-library/jest-dom](https://www.npmjs.com/package/@testing-library/jest-dom) dependency to the latest version. 
Since it is a major version upgrade, there may be some things to fix. I suggest reading over the release notes to see what has changed to ensure there is not a breaking change. Run regression tests on the components and their stories. 

Update @testing-library/jest-dom to the latest version: `  ^5.16.5  →   ^6.0.1`

<hr> 

### Contribution Guide
If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by mstruebing** [comment]
Closed by #994
