### ISSUE TITLE
Storybook Component Documentation Update - Refactor the CheckboxInput component story

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#992]
## Description
The CheckboxInput component's story is configured so that it is wrapped in the `<CheckboxStoryHelper />`. The CheckboxStoryHelper is used to manage the state and functionality of the component. 
The Code option in the component Docs page serves as a reference for how to use the component. With this HOC component wrapping it we cannot see the example of how to use this component. 
To fix this, we can move this logic into the story for the checkbox so that it allows for the `CheckboxInput` component code to display. 

The current configuration of the CheckboxInput component's story involves a <CheckboxStoryHelper /> wrapper. This wrapper plays a crucial role in overseeing the component's state and functionality.

There are some issues with how it displays the component's code in the Code tab in Storybook. This option essentially provides a guide on how to use the component. Unfortunately, the usage example of this component is obscured by the higher-order component (HOC) that is encompassing it - CheckboxStoryHelper.

<img width="1143" alt="Screenshot 2023-08-25 at 11 04 24 AM" src="https://github.com/d2iq/ui-kit/assets/34781875/48a747ff-ebdc-4d7b-8c03-9f0d70565f0b">

To address this issue, a suggested solution entails repositioning this operational logic within the story designed for the checkbox. By taking this step, the CheckboxInput component's code will become visible and accessible.

For an example of how a component was refactored in a similar way you can reference this work: https://github.com/d2iq/ui-kit/pull/989 

If this is your first experience working with Storybook stories, they have [great documentation to reference](https://storybook.js.org/docs/react/writing-stories/introduction), along with the other story files we have throughout the project. 

**Acceptance Criteria** 

Update the `CheckboxInput.stories.tsx` file so that the code example will display how to use the component. 

<hr> 

### Contribution Guide
If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by kavandalal** [comment]
Hi @nataliepina , can you please assign this task to me ?

**Comment by nataliepina** [comment]
@kavandalal assigned it to you, thanks!

**Comment by kavandalal** [comment]
@nataliepina PR created 👍
