### ISSUE TITLE
Update `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` to the latest version.

### ISSUE THREAD

**Issue by nataliepina** [d2iq/ui-kit#995]
## Description
We are a major version behind on `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser`. 
Since it is a major version upgrade, these will cause some type errors that will need to be fixed.
Please update to the latest versions and include the type fixes to complete this task. 

Update both libraries to the latest version: ` ^5.59.11  →  ^6.4.1`

<hr> 

### Contribution Guide
If this is your first time contributing to UI Kit, please review the [How to Contribute](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) guide beforehand.

**Comment by nikhilgarg26** [comment]
hey @nataliepina i would like to take up this issue, can you please guide how to start with this issue it would be a great help

**Comment by nataliepina** [comment]
Hi @nikhilgarg26 thank you for your interest. 

To start this issue i'd recommend reading over the [contribution guide](https://github.com/d2iq/ui-kit/wiki/How-to-Contribute) and getting UI Kit set up and running locally.

Next you can run `npm install @typescript-eslint/parser@latest` and `npm install @typescript-eslint/eslint-plugin@latest` to update those dependencies.

After that, run some tests by running `npm run lint` and `npm run test:types`.
There may be some type errors it will trigger after that and you can work on reading over the errors and fixing them all. 
There shouldn't be too many errors triggered, maybe around 6 the last I checked.

Let us know if you have any other questions. I'll assign it over to you now.

**Comment by nikhilgarg26** [comment]
Thanks @nataliepina for assigning this issue, i will give an update as soon as possible.

**Comment by nikhilgarg26** [comment]
@nataliepina resolved some of the issues but still getting error: `Insert `⏎···`` i guess the elslint and prettier configs are conflicting can you please help on this

**Comment by nikhilgarg26** [comment]
got it just some `--fix` i need to run

**Comment by nikhilgarg26** [comment]
![image](https://github.com/d2iq/ui-kit/assets/116938919/cabd38d4-ca25-47eb-9d34-c24295d00720)
getting this error while doing `git commit -m "update @typescript/eslint dev-dependency"` please help

**Comment by nataliepina** [comment]
Part of this work will be to resolve those eslint issues. If you're unable to, i'd suggest to get everything into a pull request and we can take a better look to help resolve the issues. It will be helpful to see the full error messages and have some additional details from your findings with this work. 

As far as the commitlint command not found error. Be sure to read over the [Contributing](https://github.com/d2iq/ui-kit/blob/main/CONTRIBUTING.md#commit-types) documentation carefully. For example, we follow conventional commits. in your example you are missing the commit type. In your case you'd want to use: `git commit -m "chore: update @typescript/eslint dev-dependency". If you update any of the code to fix the eslint errors you'd want that in a separate follow up commit that may be a refactor or fix commit depending on what you've done, `git commit -m "fix: resolved eslint issues"` Try that and make sure you've set everything up outlined in the contributing documentation, let us know if you're still having issues after that.

**Comment by nataliepina** [comment]
I noticed you closed your pull request @nikhilgarg26 are you still working on this?

I believe the way to fix the commitlint error you encountered can be to run `npm install -g @commitlint/{config-conventional,cli}`. Try that out and let us know if you need further guidance if you'd like to create another pull-request.

**Comment by nikhilgarg26** [comment]
@nataliepina i am still working on it, trying to understand issues

**Comment by nataliepina** [comment]
@nikhilgarg26 are you still working on this one? Anything we can help with?

**Comment by nataliepina** [comment]
@electron97 I believe @nikhilgarg26 was working on this. Although he hasn't responded. Can you please be sure to request for an issue to be assigned to you before created a pull request for it? This aligns with our community guidelines. Thanks.

**Comment by jaas666** [comment]
Sorry, just saw that this project uses requests for PR's I'll close mine.

**Comment by nataliepina** [comment]
No problem @jaas666, thanks, i'll add some more issues to this project soon if you'd still like to contribute on another issue.
